### ISSUE TITLE
Is this broken?

### ISSUE THREAD

**Issue by leeclemmer** [miri64/pycomicvine#6]
Hi there, I've installed and am trying to use pycomicvine, but it seems completely broken.

```
>>> import pycomicvine
>>> pycomicvine.api_key = "[my api key]"
>>> pycomicvine.Volume.search("The Walking Dead")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Volume' has no attribute 'search'
>>> pycomicvine.Search("Avengers", field_list=['name','id'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pycomicvine/__init__.py", line 451, in __repr__
    for element in self:
  File "pycomicvine/__init__.py", line 433, in __iter__
    yield self[index]
  File "pycomicvine/__init__.py", line 417, in __getitem__
    if isinstance(self._results[index], list):
IndexError: list index out of range
```

Any idea what's going on?

**Comment by miri64** [comment]
Yes, the API seems to be changing a lot. I do not however currently have any time to work on this. Will look into it, when I have.

**Comment by miri64** [comment]
Alternatively, you're welcome to open a PR to fix that. I'll find some time to review that :-)

**Comment by leeclemmer** [comment]
Ok, thanks Martine I'll see if I can find some time myself to look at it :)

**Comment by PaolaSocorro** [comment]
No one has a fix for this yet? I wanted to use for my project :/
